# This file sources other files in `hyprland` and `custom` folders.
# Put machine-specific overrides in files in `custom`.

# --- Environment variables ---
source=~/.config/hypr/hyprland/env.conf
source=~/.config/hypr/custom/env.conf

# --- Other vars ---
source=~/.config/hypr/hyprland/variables.conf
source=~/.config/hypr/custom/variables.conf

# --- Defaults ---
source=~/.config/hypr/hyprland/execs.conf
source=~/.config/hypr/hyprland/general.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/colors.conf
source=~/.config/hypr/hyprland/keybinds.conf

# --- Custom ---
source=~/.config/hypr/custom/execs.conf
source=~/.config/hypr/custom/general.conf
source=~/.config/hypr/custom/rules.conf
source=~/.config/hypr/custom/keybinds.conf

# --- Display layout ---
source=~/.config/hypr/workspaces.conf
source=~/.config/hypr/monitors.conf
