vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "View code actions" })
vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format, { desc = "Format current buffer" })
vim.keymap.set({ "n", "i" }, "<C-s>", function()
	vim.cmd("w")
end, { desc = "Save current buffer" })
vim.keymap.set("n", "<Esc>", function()
  vim.cmd("nohlsearch")
end, { desc = "Remove search highlight" })
vim.keymap.set("n", "<leader>db", function()
  vim.cmd("DapToggleBreakpoint")
end, { desc = "Add breakpoint at line" })
vim.keymap.set("n", "<leader>dr", function()
  vim.cmd("DapContinue")
end, { desc = "Start or continue the debugger" })
